replicas: 1
revisionHistoryLimit: 3

containers:
  image: gcr.io/google-samples/gb-frontend:v5
  name: guestbook-ui
  ports:
    containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 80

httpRoute:
  enabled: false

ingress:
  enabled: false
