replicas: 1
revisionHistoryLimit: 3

containers:
  image: gcr.io/google-samples/gb-frontend:v5
  name: guestbook-ui
  ports:
    containerPort: 433

service:
  type: LoadBalancer
  port: 433
  targetPort: 433

httpRoute:
  enabled: false

ingress:
  enabled: false
